config/routes.rb
InventoryApp2::Application.routes.draw do

  root to: 'static_pages#welcome'

  resources :bundle_attributes
  resources :item_features
  resources :user_comments
  resources :assignment_histories
  match 'asset_histories' => 'checkouts#index'

  match 'checkouts/assign-serial-number' => 'checkouts#assign_serial_number', as: 'serial_assignment'

  match 'about' => 'static_pages#about'

  resources :checkouts do
    resources :comments
  end
  resources :assets do
    resources :comments
  end
  resources :asset_histories
  resources :serial_numbers
  
  resources :bundles do
    resources :comments
  end
  resources :users do
    resources :comments
  end
end

app/views/shared/_analytics.html.haml
:javascript
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-39095891-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

app/views/shared/_footer.html.haml
%footer
  .m-navbar
    %ul
      %li Behind the scenes
      %li= link_to "github", "https://github.com/woodall/trakIt"
      %li |
      %li= link_to "trello stories", "https://trello.com/board/trakit/513664f6bb46d3fd770053d4"
      %li |
      %li= link_to "hireDave", "https://github.com/woodall/trakIt"

app/views/shared/_main_nav.html.haml
.container
  = link_to (image_tag "logo2.png", class: "m-header-logo"), root_path
  .m-navbar
    %ul
      %li= link_to 'Assets', assets_path
      %li= link_to 'Bundles', bundles_path
      %li= link_to 'Users', users_path
      %li= link_to 'Checkouts', checkouts_path
      %li= link_to 'Serial Numbers', serial_numbers_path
      %li
      %li= link_to 'New Asset', new_asset_path, class: 'm-new-thing'
      %li= link_to 'New checkout', new_checkout_path, class: 'm-new-thing'
      %li= link_to 'New user', new_user_path, class: 'm-new-thing'
      %li= link_to 'New bundle', new_bundle_path, class: 'm-new-thing'

app/views/shared/_typekit.html.haml
%script{:src => "//use.typekit.net/eoz0gzh.js", :type => "text/javascript"}
:javascript
  try{Typekit.load();}catch(e){}