config/routes.rb
InventoryApp2::Application.routes.draw do

  root to: 'static_pages#welcome'

  resources :bundle_attributes
  resources :item_features
  resources :user_comments
  resources :assignment_histories
  match 'asset_histories' => 'checkouts#index'

  match 'checkouts/assign-serial-number' => 'checkouts#assign_serial_number', as: 'serial_assignment'

  match 'about' => 'static_pages#about'

  resources :checkouts do
    resources :comments
  end
  resources :assets do
    resources :comments
  end
  resources :asset_histories
  resources :serial_numbers
  
  resources :bundles do
    resources :comments
  end
  resources :users do
    resources :comments
  end
end

app/models/serial_number.rb
class SerialNumber < ActiveRecord::Base
  attr_accessible :number, :warranty_end, :asset_id, :user_id, :checkout_id

  belongs_to :asset
  belongs_to :user
  belongs_to :checkout
  has_many :item_histories
  
  validates :number, presence: true

end

app/controllers/serial_numbers_controller.rb
class SerialNumbersController < ApplicationController
  def index
    @serial_numbers = SerialNumber.all

    respond_to do |format|
      format.html
      format.json { render json: @serial_numbers }
    end
  end

  def show
    @asset_history = AssetHistory.new
    @serial_number = SerialNumber.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @serial_number }
    end
  end

  def new
    @serial_number = SerialNumber.new

    respond_to do |format|
      format.html
      format.json { render json: @serial_number }
    end
  end

  def edit
    @serial_number = SerialNumber.find(params[:id])
  end

  def create
    @serial_number = SerialNumber.new(params[:serial_number])
    respond_to do |format|
      if @serial_number.save
        format.html { redirect_to asset_path(@serial_number.asset_id), notice: 'Serial number was successfully created.' }
        format.json { render json: @serial_number, status: :created, location: @serial_number }
      else
        format.html { render action: "new" }
        format.json { render json: @serial_number.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @serial_number = SerialNumber.find(params[:id])
    @asset = @serial_number.asset_id

    respond_to do |format|
      if @serial_number.update_attributes(params[:serial_number])
        format.html { redirect_to asset_path(@asset), notice: 'Serial number was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @serial_number.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @serial_number = SerialNumber.find(params[:id])
    @serial_number.destroy

    respond_to do |format|
      format.html { redirect_to serial_numbers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/serial_numbers_helper.rb
module SerialNumbersHelper
  
  #assigned_serial_number.html.haml
  def assigned_user_to_serial_number(serial_number)
    serial_number.user.name unless serial_number.user.nil?
  end

  #show 
  def serial_no
    @serial_number.asset.name unless @serial_number.asset.name.nil?
  end
end

app/views/serial_numbers/_asset_history_form.html.haml
/ = simple_form_for(@asset_history) do |f|
/   = f.error_notification

/   = f.input :serial_number_id, as: :hidden, input_html: { value: @serial_number.id }

/   .form-inputs
/     = f.input :comments

/   .form-actions
/     = f.button :submit


= form_for @asset_history do |f|
  - if @asset_history.errors.any?
    #error_explanation
      %h2= "#{pluralize(@asset_history.errors.count, "error")} prohibited this asset_history from being saved:"
      %ul
        - @asset_history.errors.full_messages.each do |msg|
          %li= msg

  = f.hidden_field :serial_number_id, value: @serial_number.id

  .field
    = f.label :comments
    = f.text_field :comments


  .actions
    = f.submit 'Save', class: "btn"

app/views/serial_numbers/_form.html.haml
= form_for @serial_number do |f|
  - if @serial_number.errors.any?
    #error_explanation
      %h2= "#{pluralize(@serial_number.errors.count, "error")} prohibited this serial_number from being saved:"
      %ul
        - @serial_number.errors.full_messages.each do |msg|
          %li= msg
  .control-group
    .field
      = f.label :number
      = f.text_field :number
    .field
      = f.label :warranty_end
      = f.date_select :warranty_end
    .actions
      = f.submit 'Save', class: "btn btn-success"

app/views/serial_numbers/edit.html.haml
%h1
  Editing
  = @serial_number.asset.name
  Serial Number:

= render 'form'

= link_to 'Show', @serial_number
\|
= link_to 'Back', serial_numbers_path

app/views/serial_numbers/index.html.haml
%h1 Listing Serial Numbers

%table.table
  %tr
    %th Asset
    %th Warranty end
    %th Number
    %th User
    %th


  - @serial_numbers.each do |serial_number|
    %tr
      %td= serial_number.asset.name
      %td= serial_number.warranty_end
      %td= link_to serial_number.number, serial_number_path(serial_number)
      %td= assigned_user_to_serial_number(serial_number)
      %td= link_to 'Destroy', serial_number, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Serial number', new_serial_number_path, class: "btn"

app/views/serial_numbers/new.html.haml
%h1 New Serial Number

= render 'form'

= link_to 'Back', serial_numbers_path

app/views/serial_numbers/show.html.haml
%p#notice= notice

%h1 Serial Number History 
%p
  %b Number:
  = @serial_number.number

%p
  %b Warranty end:
  = @serial_number.warranty_end
%p
  %b Asset:
  = serial_no
%p
  %b User:
  = assigned_user_to_serial_number(@serial_number)

= link_to 'Edit', edit_serial_number_path(@serial_number)
\|
= link_to 'Back', serial_numbers_path

= render 'asset_history_form'

-@serial_number.asset_histories.each do |entry|
  %p= entry.comments