config/routes.rb
InventoryApp2::Application.routes.draw do

  root to: 'static_pages#welcome'

  resources :bundle_attributes
  resources :item_features
  resources :user_comments
  resources :assignment_histories
  match 'asset_histories' => 'checkouts#index'

  match 'checkouts/assign-serial-number' => 'checkouts#assign_serial_number', as: 'serial_assignment'

  match 'about' => 'static_pages#about'

  resources :checkouts do
    resources :comments
  end
  resources :assets do
    resources :comments
  end
  resources :asset_histories
  resources :serial_numbers
  
  resources :bundles do
    resources :comments
  end
  resources :users do
    resources :comments
  end
end

app/models/asset.rb
class Asset < ActiveRecord::Base
  
  attr_accessible :name, :quantity, :trackable, :bundle_id

  belongs_to :bundle
  has_many :checkouts, dependent: :destroy
  has_many :users, through: :checkouts
  has_many :serial_numbers, dependent: :destroy
  has_many :item_features

  validates :quantity, presence: true

end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  def index
    @assets = Asset.all

    respond_to do |format|
      format.html 
      format.json { render json: @assets }
    end
  end

  def show
    @asset = Asset.find(params[:id])
    @serials = SerialNumber.where(asset_id: @asset)
    @checkouts = Checkout.where(asset_id: @asset)
    @feature = ItemFeature.new
    @new_serial = SerialNumber.new
 
    respond_to do |format|
      format.html 
      format.json { render json: @asset }
    end
  end

  def new
    @asset = Asset.new

    respond_to do |format|
      format.html 
      format.json { render json: @asset }
    end
  end

  def edit
    @asset = Asset.find(params[:id])
  end

  def create
    @asset_creator = AssetCreationService.new(params[:asset])
    @asset = @asset_creator.asset

    respond_to do |format|
      if @asset_creator.save
        format.html { redirect_to @asset, notice: 'Asset was successfully created.' }
        format.json { render json: @asset, status: :created, location: @asset }
      else
        format.html { render action: "new" }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @asset = Asset.find(params[:id])

    respond_to do |format|
      if @asset.update_attributes(params[:asset])
        format.html { redirect_to @asset, notice: 'Asset was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @asset = Asset.find(params[:id])
    @asset.destroy

    respond_to do |format|
      format.html { redirect_to assets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/assets_helper.rb
module AssetsHelper
  def link_to_user(asset)
    unless asset.user.nil?
      link_to asset.user.name, user_path(asset.user)
    else
      ""
    end
  end
end

app/views/assets/_add_feature.html.haml
= simple_form_for(@feature) do |f|
  = f.error_notification

  .form-inputs
    = f.input :feature_key, label: "Label"
    = f.input :feature_value, label: "Value"
    = f.input :asset_id, as: :hidden, input_html: { value: @asset.id }

  .form-actions
    = f.button :submit, "Add Asset Attribute", class: "btn btn-success"

app/views/assets/_form.html.haml
= form_for @asset do |f|
  - if @asset.errors.any?
    #error_explanation
      %h2= "#{pluralize(@asset.errors.count, "error")} prohibited this asset from being saved:"
      %ul
        - @asset.errors.full_messages.each do |msg|
          %li= msg

  .control-group
    .field
      = f.label :bundle_id
      = f.collection_select :bundle_id, Bundle.all, :id, :name
      = link_to "Or, add a new bundle", new_bundle_path
    .field
      = f.label :name
      = f.text_field :name
    .field
      = f.label :trackable
      = f.check_box :trackable
    .field
      = f.label :quantity
      = f.number_field :quantity
    .actions.form-actions
      = f.submit 'Save', class: "btn"

app/views/assets/_form_edit_asset.html.haml
= form_for @asset do |f|
  - if @asset.errors.any?
    #error_explanation
      %h2= "#{pluralize(@asset.errors.count, "error")} prohibited this asset from being saved:"
      %ul
        - @asset.errors.full_messages.each do |msg|
          %li= msg
  
  .control-group
    .field
      = f.label :name
      = f.text_field :name

    .field
      = f.label :bundle
      = f.collection_select :bundle_id, Bundle.all, :id, :name
  
  .actions.form-actions
    = f.submit 'Save', class: "btn btn-success"

app/views/assets/_form_new_serial.html.haml
- if @asset.trackable?
  = simple_form_for(@new_serial) do |f|
    = f.error_notification

    .form-inputs
      = f.input :asset_id, as: :hidden, input_html: { value: @asset.id }
      = f.input :number
      = f.input :warranty_end

    .form-actions
      = f.button :submit, class: "btn btn-success"

app/views/assets/_trackable_table.html.haml
- if @asset.trackable?

  %h3 Serial Numbers
  %table.table
    %tr
      %th Number
      %th Date Created
      %th Warranty End
      %th Assigned to

    - @serials.each do |asset|
      %tr
        %td= link_to asset.number, edit_serial_number_path(asset)
        %td= asset.created_at.strftime('%B %e')
        %td= asset.warranty_end
        %td= link_to_user(asset)

app/views/assets/edit.html.haml
.container.fluid
  .row-fluid
    %h1 Editing asset
    .form-horizontal
      = render 'form_edit_asset'

      = link_to 'Show', @asset
      \|
      = link_to 'Back', assets_path, class: "btn back-btn"

app/views/assets/index.html.haml
%h1 Listing assets
%table
  %tr
    %th Name
    %th Available Quantity
    %th Bundle
    %th
    %th
    %th

  - @assets.each do |asset|
    %tr
      %td= link_to asset.name, asset
      %td= asset.quantity
      %td= link_to asset.bundle.name, asset.bundle
      %td
      %td= link_to 'Edit', edit_asset_path(asset)
      %td= link_to 'Destroy', asset, method: :delete, data: { confirm: 'Are you sure?' }

= link_to 'New Asset', new_asset_path, class: "btn"

app/views/assets/new.html.haml
.container.fluid
  .row-fluid
    .form-horizontal
    %h1 New Asset

    = render 'form'

    = link_to 'Back', assets_path, class: "btn back-btn"

app/views/assets/show.html.haml
%p#notice= notice

%h1= link_to @asset.name, edit_asset_path(@asset)

.row
  %p
  %b Available Stock: 
  = @asset.quantity

  %p
  %b Bundle:
  = link_to @asset.bundle.name, bundle_path(@asset.bundle)

  - @asset.item_features.each do |feature|
    %p
      %b=feature.feature_key
      \:
      =link_to feature.feature_value, edit_item_feature_path(feature)

  = render 'add_feature'

= render 'trackable_table'
= render 'form_new_serial'