config/routes.rb
InventoryApp2::Application.routes.draw do

  root to: 'static_pages#welcome'

  resources :bundle_attributes
  resources :item_features
  resources :user_comments
  resources :assignment_histories
  match 'asset_histories' => 'checkouts#index'

  match 'checkouts/assign-serial-number' => 'checkouts#assign_serial_number', as: 'serial_assignment'

  match 'about' => 'static_pages#about'

  resources :checkouts do
    resources :comments
  end
  resources :assets do
    resources :comments
  end
  resources :asset_histories
  resources :serial_numbers
  
  resources :bundles do
    resources :comments
  end
  resources :users do
    resources :comments
  end
end

app/models/checkout.rb
class Checkout < ActiveRecord::Base
  attr_accessible :name, :quantity, :status, :user_id, :asset_id, 
                  :checkout_serial, :due_date
  
  belongs_to :user
  belongs_to :asset
  has_many :serial_numbers
  has_many :assignment_histories

  validates :quantity, presence: true
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  def index
    @checkouts = Checkout.all

    respond_to do |format|
      format.html 
      format.json { render json: @checkouts }
    end
  end

  def show
    @checkout = Checkout.find(params[:id])
    @assignment = AssignmentHistory.new
    
    respond_to do |format|
      format.html 
      format.json { render json: @checkout }
    end
  end

  def new
    @checkout = Checkout.new

    respond_to do |format|
      format.html 
      format.json { render json: @checkout }
    end
  end

  def edit
    @checkout = Checkout.find(:last)
  end

  def create
    @quantity_reducer = CheckoutQuantityReducerService.new(params[:checkout])
    @checkout = Checkout.new(params[:checkout])

    respond_to do |format|
      
      if @quantity_reducer.save
        if @checkout.asset.trackable?
          format.html { redirect_to serial_assignment_path, notice: 'Checkout was successfully created.' }
          format.json { render json: @checkout, status: :created, location: @checkout }
        else
          format.html { redirect_to checkouts_path, notice: 'Checkout was successfully created.' }
        end
      else
        format.html { render action: "new" }
        format.json { render json: @checkout.errors, status: :unprocessable_entity }
      end
    end
  end

  def assign_serial_number
     @checkout = Checkout.find(:last)
     @serial_number = SerialNumber.all
  end

  def update
    @checkout = Checkout.find(params[:id])

    respond_to do |format|
      if @checkout.update_attributes(params[:checkout])
        format.html { redirect_to @checkout, notice: 'Checkout was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @checkout.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @checkout = Checkout.find(params[:id])
    @checkout.destroy

    respond_to do |format|
      format.html { redirect_to checkouts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
  def checkout_dates
    [['1 week',"#{1.week.from_now}"], ['2 weeks',"#{2.weeks.from_now}"], ['3 weeks',"#{3.weeks.from_now}"], ['1 month',"#{1.month.from_now}"], ['2 months',"#{2.months.from_now}"], ['3 months',"#{3.months.from_now}"], ['4 months',"#{4.months.from_now}"], ['5 months',"#{5.months.from_now}"], ['6 months',"#{6.months.from_now}"]]
  end

  def due_date(checkout)
    checkout.due_date.strftime("%B %e") unless checkout.due_date.nil?
  end

  def remaining_time_of_rental(checkout) 
    distance_of_time_in_words(Time.now, checkout.due_date) unless checkout.due_date.nil?
  end
end

app/views/checkouts/_form.html.haml
= form_for @checkout do |f|
  - if @checkout.errors.any?
    #error_explanation
      %h2= "#{pluralize(@checkout.errors.count, "error")} prohibited this checkout from being saved:"
      %ul
        - @checkout.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_id
    = f.collection_select :user_id, User.all, :id, :name
    = link_to "Or, add a new user", new_user_path
  .field
    = f.label :asset_id
    = f.collection_select :asset_id, Asset.all, :id, :name
    = link_to "Or, add a new asset", new_asset_path
  .field
    = f.label :quantity
    = f.number_field :quantity
  .field
    = f.label :status
    = f.text_field :status
  .field
    = f.label :due_date
    = f.select :due_date, options_for_select(checkout_dates), :include_blank => true


  .actions
    = f.submit 'Save', class: "btn"

app/views/checkouts/assign_serial_number.html.haml
/ TODO - create a call back that saves user, so that it's assigned at step 2.

%h1 Step 2, pick your serial number

%table.table
  %tr
    %th Number
    %th Current User

  -@checkout.asset.serial_numbers.each do |serial_number|
    %tr
      %td= link_to serial_number.number, edit_serial_number_path(serial_number)
      %td= assigned_user_to_serial_number(serial_number) 

app/views/checkouts/edit.html.haml
%h1 Editing checkout

= form_for @checkout do |f|
  - if @checkout.errors.any?
    #error_explanation
      %h2= "#{pluralize(@checkout.errors.count, "error")} prohibited this checkout from being saved:"
      %ul
        - @checkout.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.collection_select :user_id, User.all, :id, :name
  .field
    = f.label :asset_name
    = f.collection_select :asset_id, Asset.all, :id, :name
  .field
    = f.label :quantity
    = f.number_field :quantity
  .field
    = f.label :status
    = f.text_field :status
  .field
    = f.label :Due_Date
    = f.datetime_select :due_date
  / .field
  /   = f.label :Due_Date
  /   = f.select :due_date, options_for_select(checkout_dates), :include_blank => true

  .actions
    = f.submit 'Save', class: "btn"


= link_to 'Show', @checkout
\|
= link_to 'Back', checkouts_path, class: "btn back-btn"

app/views/checkouts/index.html.haml
%h1 Listing checkouts

%table.table
  %tr
    %th Date Out
    %th User
    %th Asset
    %th Due Date
    %th Status


  - @checkouts.each do |checkout|
    %tr
      %td= link_to checkout.created_at.strftime("%b %e"), checkout
      %td= checkout.user.name
      %td= checkout.asset.name
      %td
        = remaining_time_of_rental(checkout)
        \(
        = due_date(checkout)
        \)
      %td= checkout.status
      %td= link_to 'Edit', edit_checkout_path(checkout)
      %td= link_to 'Destroy', checkout, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Checkout', new_checkout_path, class: "btn"

app/views/checkouts/new.html.haml
%h1 New Assignment

= render 'form'

= link_to 'Back', checkouts_path, class: "btn back-btn"

app/views/checkouts/show.html.haml
%p#notice= notice

%h1 Assignment History

%table.table
  %tr
    %th Date
    %th User
    %th Asset
    %th Quantity
    %th Serial Number
    %th Status
    %th Comments

  %tr
    %td=  @checkout.user.created_at.strftime('%B %e')
    %td=  @checkout.user.name
    %td=  @checkout.asset.name
    %td=  @checkout.quantity
    %td=  @checkout.checkout_serial
    %td=  @checkout.status

= link_to 'Edit', edit_checkout_path(@checkout)
\|
= link_to 'Back', checkouts_path, class: "btn back-btn"

= render 'assignment_histories/form'

- @checkout.assignment_histories.each do |historical|
  %p
  = historical.note
  \-
  = historical.created_at.strftime("%B %e")